name: Django CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ecommerce_test
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django coverage
        
    - name: Run migrations
      run: python manage.py migrate
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/ecommerce_test
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        
    - name: Run tests
      run: |
        python -m pytest --cov=.
        coverage xml
      env:
        AFRICASTALKING_USERNAME: test
        AFRICASTALKING_API_KEY: test
        ENABLE_SMS: "False"
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3